# Generated by Django 5.1.1 on 2024-10-18 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockhistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['vendor', 'category', 'name', 'stock'], name='products_pr_vendor__90421d_idx'),
        ),
    ]
