# Generated by Django 5.1.1 on 2024-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vendor', 'Vendor'), ('Customer', 'Customer')], default='Admin', max_length=20),
        ),
    ]
